### PR TITLE
Revert "use SP saved in context, avoids problems when on alternate signal stack"

### PR DESCRIPTION
**Pull request by dbuckley3d**
Reverts Unity-Technologies/bdwgc#26

### CODE REVIEW

**Comment by joshpeterson** [comment]
Can you add information in the commit message about why we need to revert this?

**Comment by dbuckley3d** [comment]
This change results in corruption of the heap.

**Comment by joshpeterson** [comment]
Ok, let's wait for Jonathan to review as well.

**Comment by joncham** [comment]
Do we just want to revert and not provide alternative fix?

**Comment by dbuckley3d** [comment]
Yes.  We don't have an alternate fix at the moment.

**Comment by joncham** [comment]
Did we never apply this yet @dbuckley3d ?

**Pull request merged**
